---
- name: Adicionando repositorio do PostgreSQL
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
    state: present

- name: Adicionando chave GPG do PostgreSQL
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Instalando banco de dados PostgreSQL
  apt:
    name: [postgresql, postgresql-contrib, python-psycopg2]
    state: present
    update_cache: yes
...