---
- name: Checando se pasta base existe
  command: "test -e {{ svn_root }}/{{ repositorio }}"
  ignore_errors: yes
  register: repo

- name: Criando pasta root
  file:
    path: "{{ svn_root }}/{{ repositorio }}"
    state: directory
    mode: 0755
  when: repo.rc != 0

- name: Subindo container Docker
  docker_container:
    name: "{{ repositorio }}"
    image: svn:1.8
    volumes: 
      - "{{ svn_root }}/{{ repositorio }}:/home/svn/repo"
      - "{{ pasta_banco }}:/home/database"
      - "{{ pasta_backup }}:/home/backup"
    state: started
    ports:
      - "3690:3690"

- name: Criando o repositorio base
  command: "docker exec {{ repositorio }} svnadmin create {{ svn_root }}/repo"
  when: repo.rc != 0

- name: Fazendo WGET svnserve.conf
  get_url:
    url: "{{ svnserve }}"
    dest: "{{ svn_root }}/{{ repositorio }}/conf/svnserve.conf"
    mode: 0644
    force: yes

- name: Fazendo WGET do AuthZ
  get_url:
    url: "{{ authz }}"
    dest: "{{ svn_root }}/{{ repositorio }}/conf/authz"
    mode: 0644
    force: yes
...